export enum Screens {
  MAIN_APP = 'MAIN_APP',

  HOME_MAIN = 'HOME_MAIN',
  HOME_DETAIL = 'HOME_DETAIL',

  SECOND_MAIN = 'SECOND_MAIN',
  SECOND_DETAIL = 'SECOND_DETAIL',

  KIT_MAIN = 'KIT_MAIN',

  AUTH_STACK = 'AUTH_STACK',
  AUTH_START = 'AUTH_START',
}
